/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const ModelHome =(props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/modelHome.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="modelHome" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="4f82679ca81b4191958360ab6dd32fecfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.025}>
            <group name="RootNode">
              <group name="Box001" position={[43.296, 0, 6.474]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box001_Solid_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Box001_Solid_Glass_0.geometry}
                  material={materials.Solid_Glass}
                />
              </group>
              <group
                name="Box002"
                position={[43.296, 118.11, 6.474]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box002_Solid_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Box002_Solid_Glass_0.geometry}
                  material={materials.Solid_Glass}
                  scale={[0.988, 1, 1]}
                />
              </group>
              <group name="Box003" position={[58.393, 0, -112.198]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box003_Metal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Box003_Metal_0.geometry}
                  material={materials.Metal}
                  position={[-34.56, 0, 0]}
                  scale={[1.035, 1, 1]}
                />
              </group>
              <group
                name="Box004"
                position={[131.967, 0, -364.257]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                <mesh
                  name="Box004_Solid_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Box004_Solid_Glass_0.geometry}
                  material={materials.Solid_Glass}
                />
              </group>
              <group
                name="Box005"
                position={[-203.854, 0.764, 128.479]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box005_Wall_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Box005_Wall_Paint_0.geometry}
                  material={materials.Wall_Paint}
                />
              </group>
              <group
                name="Box006"
                position={[6.414, 0.764, 128.479]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box006_Wall_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Box006_Wall_Paint_0.geometry}
                  material={materials.Wall_Paint}
                />
              </group>
              <group name="Box008" position={[4.874, 0, -202.658]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box008_04_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box008_04_-_Default_0'].geometry}
                  material={materials['04_-_Default']}
                />
              </group>
              <group
                name="Box011"
                position={[128.321, 137.156, -201.652]}
                rotation={[0, -1.571, 0]}>
                <mesh
                  name="Box011__0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Box011__0.geometry}
                  material={materials.Box011__0}
                />
              </group>
              <group
                name="Box012"
                position={[-16.078, 1.426, 229.815]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <group
                name="Box013"
                position={[124.193, 1.426, 229.815]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <group
                name="Box014"
                position={[269.548, 1.426, 229.815]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box014_12_-_Car_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box014_12_-_Car_Paint_0'].geometry}
                  material={materials['12_-_Car_Paint']}
                />
              </group>
              <group
                name="Box016"
                position={[405.875, 1.426, 229.815]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box016_12_-_Car_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box016_12_-_Car_Paint_0'].geometry}
                  material={materials['12_-_Car_Paint']}
                />
              </group>
              <group
                name="Box017"
                position={[405.875, 1.426, 76.799]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box017_12_-_Car_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box017_12_-_Car_Paint_0'].geometry}
                  material={materials['12_-_Car_Paint']}
                />
              </group>
              <group
                name="Box018"
                position={[405.875, 1.426, -76.216]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box018_12_-_Car_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box018_12_-_Car_Paint_0'].geometry}
                  material={materials['12_-_Car_Paint']}
                />
              </group>
              <group
                name="Box019"
                position={[405.875, 1.426, -229.232]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box019_12_-_Car_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box019_12_-_Car_Paint_0'].geometry}
                  material={materials['12_-_Car_Paint']}
                />
              </group>
              <group
                name="Box020"
                position={[405.875, 1.426, -382.248]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box020_12_-_Car_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box020_12_-_Car_Paint_0'].geometry}
                  material={materials['12_-_Car_Paint']}
                />
              </group>
              <group
                name="Box021"
                position={[405.875, 1.426, -520.514]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box021_12_-_Car_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box021_12_-_Car_Paint_0'].geometry}
                  material={materials['12_-_Car_Paint']}
                />
              </group>
              <group
                name="Box022"
                position={[268.994, 1.426, -421.658]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box022_12_-_Car_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box022_12_-_Car_Paint_0'].geometry}
                  material={materials['12_-_Car_Paint']}
                  position={[0, 0, -1.275]}
                />
              </group>
              <group
                name="Box023"
                position={[58.393, -1.533, -112.198]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box023_24_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box023_24_-_Default_0'].geometry}
                  material={materials['24_-_Default']}
                  position={[-34.56, 0, 0]}
                  scale={[1.035, 1, 1]}
                />
              </group>
              <group
                name="Box024"
                position={[-15.151, 127.028, -85.841]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box024_21_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box024_21_-_Default_0'].geometry}
                  material={materials['21_-_Default']}
                />
              </group>
              <group
                name="Box025"
                position={[-207.05, 127.028, -85.841]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box025_21_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box025_21_-_Default_0'].geometry}
                  material={materials['21_-_Default']}
                />
              </group>
              <group
                name="Box026"
                position={[-207.05, 127.028, 131.501]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box026_21_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box026_21_-_Default_0'].geometry}
                  material={materials['21_-_Default']}
                />
              </group>
              <group
                name="Box027"
                position={[-2.817, 127.028, 131.501]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box027_21_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box027_21_-_Default_0'].geometry}
                  material={materials['21_-_Default']}
                />
              </group>
              <group
                name="Box028"
                position={[316.737, 127.028, 131.501]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box028_21_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box028_21_-_Default_0'].geometry}
                  material={materials['21_-_Default']}
                />
              </group>
              <group
                name="Box029"
                position={[316.737, 127.028, 24.979]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Box029_21_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Box029_21_-_Default_0'].geometry}
                  material={materials['21_-_Default']}
                />
              </group>
              <group
                name="Line002"
                position={[269.538, 185.642, 0]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}>
                <mesh
                  name="Line002_03_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Line002_03_-_Default_0'].geometry}
                  material={materials['03_-_Default']}
                />
              </group>
              <group
                name="Line003"
                position={[-138.862, 13.668, -42.765]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Line003_Wall_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Line003_Wall_Paint_0.geometry}
                  material={materials.Wall_Paint}
                />
              </group>
              <group name="Line004" position={[159.865, 129.134, 6.812]}>
                <mesh
                  name="Line004_02_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Line004_02_-_Default_0'].geometry}
                  material={materials['02_-_Default']}
                />
              </group>
              <group name="Line005" position={[159.865, 129.134, -344.332]}>
                <mesh
                  name="Line005_02_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Line005_02_-_Default_0'].geometry}
                  material={materials['02_-_Default']}
                />
              </group>
              <group
                name="Line006"
                position={[246.268, 13.668, 103.95]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Line006_Wall_Paint_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Line006_Wall_Paint_0.geometry}
                  material={materials.Wall_Paint}
                />
              </group>
              <group
                name="Line007"
                position={[-191.039, 1.536, -45.281]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Line007_11_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Line007_11_-_Default_0'].geometry}
                  material={materials['11_-_Default']}
                  position={[82.055, 0, 0]}
                  scale={[1.855, 1, 1]}
                />
              </group>
              <group
                name="Line008"
                position={[96.57, 127.024, -198.022]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Line008_05_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Line008_05_-_Default_0'].geometry}
                  material={materials['05_-_Default']}
                  scale={[0.951, 1, 1]}
                />
              </group>
              <group
                name="Line009"
                position={[35.711, 125.71, 20.383]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Line009_06_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Line009_06_-_Default_0'].geometry}
                  material={materials['06_-_Default']}
                />
              </group>
              <group
                name="Line010"
                position={[35.526, 7.053, 19.414]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Line010_05_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Line010_05_-_Default_0'].geometry}
                  material={materials['05_-_Default']}
                />
              </group>
              <group
                name="Line011"
                position={[96.57, 6.975, -198.022]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Line011_05_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Line011_05_-_Default_0'].geometry}
                  material={materials['05_-_Default']}
                />
              </group>
              <group
                name="Line012"
                position={[42.785, 143.902, 21.72]}
                rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="Line012_23_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Line012_23_-_Default_0'].geometry}
                  material={materials['23_-_Default']}
                />
              </group>
              <group
                name="Plane001"
                position={[16.968, 137.156, -201.652]}
                rotation={[0, -1.571, 0]}>
                <mesh
                  name="Plane001_01_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Plane001_01_-_Default_0'].geometry}
                  material={materials['01_-_Default']}
                />
              </group>
              <group
                name="Shape001"
                position={[-32.775, 137.156, -201.652]}
                rotation={[0, -1.571, 0]}>
                <mesh
                  name="Shape001_02_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Shape001_02_-_Default_0'].geometry}
                  material={materials['02_-_Default']}
                />
              </group>
              <group name="Shape002" position={[159.865, 129.134, 3.345]}>
                <mesh
                  name="Shape002_01_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Shape002_01_-_Default_0'].geometry}
                  material={materials['01_-_Default']}
                />
              </group>
              <group
                name="Shape003"
                position={[159.724, 129.134, 3.345]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}>
                <mesh
                  name="Shape003_01_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Shape003_01_-_Default_0'].geometry}
                  material={materials['01_-_Default']}
                />
              </group>
              <group name="Shape004" position={[159.865, 129.134, 2.813]}>
                <mesh
                  name="Shape004_01_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Shape004_01_-_Default_0'].geometry}
                  material={materials['01_-_Default']}
                />
              </group>
              <group name="Shape005" position={[159.865, 129.134, -351.227]}>
                <mesh
                  name="Shape005_01_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Shape005_01_-_Default_0'].geometry}
                  material={materials['01_-_Default']}
                />
              </group>
              <group
                name="Shape006"
                position={[159.724, 129.134, -351.227]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}>
                <mesh
                  name="Shape006_01_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Shape006_01_-_Default_0'].geometry}
                  material={materials['01_-_Default']}
                />
              </group>
              <group name="Shape007" position={[159.865, 129.134, -351.759]}>
                <mesh
                  name="Shape007_01_-_Default_0"
                  castShadow
                  receiveShadow
                  geometry={nodes['Shape007_01_-_Default_0'].geometry}
                  material={materials['01_-_Default']}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="toldo"
          position={[-2.648, 2.201, 5.033]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.018}>
          <group name="awning_bracketobjcleanermaterialmergergles">
            <mesh
              name="Object_2"
              castShadow
              receiveShadow
              geometry={nodes.Object_2.geometry}
              material={materials.Waterboard}
            />
            <mesh
              name="Object_3"
              castShadow
              receiveShadow
              geometry={nodes.Object_3.geometry}
              material={materials.Canvas}
            />
            <mesh
              name="Object_4"
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.Hinges}
            />
            <mesh
              name="Object_5"
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials['Metal.001']}
            />
          </group>
        </group>
        <group
          name="toldo2"
          position={[4.163, 2.164, 4.976]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.025, 0.019, 0.019]}>
          <group name="awning_bracketobjcleanermaterialmergergles001">
            <mesh
              name="Object_2001"
              castShadow
              receiveShadow
              geometry={nodes.Object_2001.geometry}
              material={materials['Waterboard.002']}
            />
            <mesh
              name="Object_3001"
              castShadow
              receiveShadow
              geometry={nodes.Object_3001.geometry}
              material={materials['Canvas.002']}
            />
            <mesh
              name="Object_4001"
              castShadow
              receiveShadow
              geometry={nodes.Object_4001.geometry}
              material={materials['Hinges.002']}
            />
            <mesh
              name="Object_5001"
              castShadow
              receiveShadow
              geometry={nodes.Object_5001.geometry}
              material={materials['Metal.003']}
            />
          </group>
        </group>
        <group
          name="mesita"
          position={[-2.523, 0, 0.549]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.038}>
          <group name="Collada_visual_scene_group">
            <group name="SketchUp">
              <group name="group_0" position={[-36.009, -36.92, -0.159]}>
                <group name="instance_16" position={[25.433, 51.289, 0]} rotation={[0, 0, 0.034]}>
                  <group
                    name="instance_10001"
                    position={[2.5, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={-1}>
                    <mesh
                      name="Material2020"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2020.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_11001" position={[2, 0.24, 18.134]}>
                    <mesh
                      name="Material2021"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2021.geometry}
                      material={materials.Color_C09}
                    />
                  </group>
                  <group name="instance_12001" position={[2.5, 20.274, 36.655]}>
                    <mesh
                      name="Material2022"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2022.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_13001" position={[2.5, 18.618, 28.224]}>
                    <mesh
                      name="Material2023"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2023.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_14001" position={[2.5, 19.722, 33.845]}>
                    <mesh
                      name="Material2024"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2024.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_15001" position={[2.5, 19.17, 31.034]}>
                    <mesh
                      name="Material2025"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2025.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_9001" position={[18, 0, 0]}>
                    <mesh
                      name="Material2019"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2019.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                </group>
                <group name="instance_17" position={[44.92, 21.043, 0]} rotation={[0, 0, Math.PI]}>
                  <group
                    name="instance_10002"
                    position={[2.5, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={-1}>
                    <mesh
                      name="Material2027"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2027.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_11002" position={[2, 0.24, 18.134]}>
                    <mesh
                      name="Material2028"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2028.geometry}
                      material={materials.Color_C09}
                    />
                  </group>
                  <group name="instance_12002" position={[2.5, 20.274, 36.655]}>
                    <mesh
                      name="Material2029"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2029.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_13002" position={[2.5, 18.618, 28.224]}>
                    <mesh
                      name="Material2030"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2030.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_14002" position={[2.5, 19.722, 33.845]}>
                    <mesh
                      name="Material2031"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2031.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_15002" position={[2.5, 19.17, 31.034]}>
                    <mesh
                      name="Material2032"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2032.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_9002" position={[18, 0, 0]}>
                    <mesh
                      name="Material2026"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2026.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                </group>
                <group
                  name="instance_18"
                  position={[21.043, 27.355, 0]}
                  rotation={[0, 0, Math.PI / 2]}>
                  <group
                    name="instance_10003"
                    position={[2.5, 0, 0]}
                    rotation={[Math.PI, 0, 0]}
                    scale={-1}>
                    <mesh
                      name="Material2034"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2034.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_11003" position={[2, 0.24, 18.134]}>
                    <mesh
                      name="Material2035"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2035.geometry}
                      material={materials.Color_C09}
                    />
                  </group>
                  <group name="instance_12003" position={[2.5, 20.274, 36.655]}>
                    <mesh
                      name="Material2036"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2036.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_13003" position={[2.5, 18.618, 28.224]}>
                    <mesh
                      name="Material2037"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2037.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_14003" position={[2.5, 19.722, 33.845]}>
                    <mesh
                      name="Material2038"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2038.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_15003" position={[2.5, 19.17, 31.034]}>
                    <mesh
                      name="Material2039"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2039.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_9003" position={[18, 0, 0]}>
                    <mesh
                      name="Material2033"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2033.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                </group>
                <group name="instance_8" position={[49.569, 49.057, 0]} rotation={[0, 0, -1.66]}>
                  <group
                    name="instance_10"
                    position={[2.5, 0, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={-1}>
                    <mesh
                      name="Material2013"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2013.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_11" position={[2, 0.239, 18.134]}>
                    <mesh
                      name="Material2014"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2014.geometry}
                      material={materials.Color_C09}
                    />
                  </group>
                  <group name="instance_12" position={[2.5, 20.274, 36.655]}>
                    <mesh
                      name="Material2015"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2015.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_13" position={[2.5, 18.618, 28.224]}>
                    <mesh
                      name="Material2016"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2016.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_14" position={[2.5, 19.722, 33.845]}>
                    <mesh
                      name="Material2017"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2017.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_15" position={[2.5, 19.17, 31.034]}>
                    <mesh
                      name="Material2018"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2018.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_9" position={[18, 0, 0]}>
                    <mesh
                      name="Material2012"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2012.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                </group>
                <group
                  name="Table"
                  position={[15.009, 74.92, 0]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={-1}>
                  <group name="instance_0" position={[25.584, 32.481, 0]} rotation={[0, 0, -1.368]}>
                    <mesh
                      name="Material2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_1" position={[15.87, 33.026, 0]} rotation={[0, 0, -2.962]}>
                    <mesh
                      name="Material2001"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2001.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_2" position={[1.557, 18.315, 32.5]}>
                    <group name="group_1" position={[0, 0, 1.5]}>
                      <mesh
                        name="Material2003"
                        castShadow
                        receiveShadow
                        geometry={nodes.Material2003.geometry}
                        material={materials.Vidrio}
                      />
                      <mesh
                        name="Material2004"
                        castShadow
                        receiveShadow
                        geometry={nodes.Material2004.geometry}
                        material={materials.Vidrio}
                      />
                    </group>
                    <mesh
                      name="Material2002"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2002.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_3" position={[13.028, 29.929, 20.872]}>
                    <mesh
                      name="Material2005"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2005.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                </group>
                <group name="Table001" position={[15.009, -1.08, 0]}>
                  <group name="instance_4" position={[25.584, 32.481, 0]} rotation={[0, 0, -1.368]}>
                    <mesh
                      name="Material2006"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2006.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_5" position={[15.87, 33.026, 0]} rotation={[0, 0, -2.962]}>
                    <mesh
                      name="Material2007"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2007.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_6" position={[1.557, 18.315, 32.5]}>
                    <group name="group_1001" position={[0, 0, 1.5]}>
                      <mesh
                        name="Material2009"
                        castShadow
                        receiveShadow
                        geometry={nodes.Material2009.geometry}
                        material={materials.Vidrio}
                      />
                      <mesh
                        name="Material2010"
                        castShadow
                        receiveShadow
                        geometry={nodes.Material2010.geometry}
                        material={materials.Vidrio}
                      />
                    </group>
                    <mesh
                      name="Material2008"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2008.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                  <group name="instance_7" position={[13.028, 29.929, 20.872]}>
                    <mesh
                      name="Material2011"
                      castShadow
                      receiveShadow
                      geometry={nodes.Material2011.geometry}
                      material={materials['0135_gris_mximo']}
                    />
                  </group>
                </group>
              </group>
              <group
                name="skp_camera_Last_Saved_SketchUp_View"
                position={[52.511, -52.833, 112.768]}
                rotation={[0.532, 0.444, 0.63]}>
                <group name="ID1" />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Pergola"
          position={[-11.088, 0.137, -9.579]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.001}>
          <group
            name="3ce74f31fd3a42bea547c4fe34622b52fbx"
            position={[0.001, 0, 0]}
            rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001" position={[0, 0, 0]}>
              <group name="Model" position={[0, 0, 0]}>
                <group name="Group1" position={[0, 0, 0]}>
                  <group name="Mesh1" position={[0, 0, 0]} />
                </group>
                <group name="Group2" position={[0, 0, 0]}>
                  <group name="Mesh2" position={[0, 0, 0]} />
                </group>
                <group name="Group3" position={[0, 0, 0]}>
                  <group name="__________________1" position={[0, 0, 0]}>
                    <group name="Group22" position={[0, 0, 0]}>
                      <group name="Mesh20" position={[0, 0, 0]} />
                    </group>
                    <group name="Group23" position={[0, 0, 0]}>
                      <group name="Mesh21" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh21_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh21_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, -96.896, 0]}
                          scale={[1, 1.104, 1]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________2" position={[0, 0, 0]}>
                    <group name="Group24" position={[0, 0, 0]}>
                      <group name="Mesh22" position={[0, 0, 0]} />
                    </group>
                    <group name="Group25" position={[0, 0, 0]}>
                      <group name="Mesh23" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh23_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh23_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, -96.896, 0]}
                          scale={[1, 1.104, 1]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________3" position={[0, 0, 0]}>
                    <group name="Group26" position={[0, 0, 0]}>
                      <group name="Mesh24" position={[0, 0, 0]} />
                    </group>
                    <group name="Group27" position={[0, 0, 0]}>
                      <group name="Mesh25" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh25_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh25_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, -96.896, 0]}
                          scale={[1, 1.104, 1]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________4" position={[0, 0, 0]}>
                    <group name="Group28" position={[0, 0, 0]}>
                      <group name="Mesh26" position={[0, 0, 0]} />
                    </group>
                    <group name="Group29" position={[0, 0, 0]}>
                      <group name="Mesh27" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh27_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh27_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, -96.896, 0]}
                          scale={[1, 1.104, 1]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________5" position={[0, 0, 0]}>
                    <group name="Group30" position={[0, 0, 0]}>
                      <group name="Mesh28" position={[0, 0, 0]} />
                    </group>
                    <group name="Group31" position={[0, 0, 0]}>
                      <group name="Mesh29" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh29_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh29_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, -96.896, 0]}
                          scale={[1, 1.104, 1]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________6" position={[0, 0, 0]}>
                    <group name="Group32" position={[0, 0, 0]}>
                      <group name="Mesh30" position={[0, 0, 0]} />
                    </group>
                    <group name="Group33" position={[0, 0, 0]}>
                      <group name="Mesh31" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh31_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh31_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, -96.896, 0]}
                          scale={[1, 1.104, 1]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________7" position={[0, 0, 0]}>
                    <group name="Group34" position={[0, 0, 0]}>
                      <group name="Mesh32" position={[0, 0, 0]} />
                    </group>
                    <group name="Group35" position={[0, 0, 0]}>
                      <group name="Mesh33" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh33_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh33_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, -96.896, 0]}
                          scale={[1, 1.104, 1]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________8" position={[0, 0, 0]}>
                    <group name="Group36" position={[0, 0, 0]}>
                      <group name="Mesh34" position={[0, 0, 0]} />
                    </group>
                    <group name="Group37" position={[0, 0, 0]}>
                      <group name="Mesh35" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh35_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh35_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, -96.896, 0]}
                          scale={[1, 1.104, 1]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________9" position={[0, 0, 0]}>
                    <group name="Group38" position={[0, 0, 0]}>
                      <group name="Mesh36" position={[0, 0, 0]} />
                    </group>
                    <group name="Group39" position={[0, 0, 0]}>
                      <group name="Mesh37" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh37_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh37_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, -96.896, 0]}
                          scale={[1, 1.104, 1]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="Group4" position={[0, 0, 0]}>
                    <group name="Group10" position={[0, 0, 0]}>
                      <group name="Mesh8" position={[0, 0, 0]} />
                    </group>
                    <group name="Group11" position={[0, 0, 0]}>
                      <group name="Mesh9" position={[0, 0, 0]} />
                    </group>
                    <group name="Group12" position={[0, 0, 0]}>
                      <group name="Mesh10" position={[0, 0, 0]} />
                    </group>
                    <group name="Group13" position={[0, 0, 0]}>
                      <group name="Mesh11" position={[0, 0, 0]} />
                    </group>
                    <group name="Group14" position={[0, 0, 0]}>
                      <group name="Mesh12" position={[0, 0, 0]} />
                    </group>
                    <group name="Group15" position={[0, 0, 0]}>
                      <group name="Mesh13" position={[0, 0, 0]} />
                    </group>
                    <group name="Group16" position={[0, 0, 0]}>
                      <group name="Mesh14" position={[0, 0, 0]} />
                    </group>
                    <group name="Group17" position={[0, 0, 0]}>
                      <group name="Mesh15" position={[0, 0, 0]} />
                    </group>
                    <group name="Group18" position={[0, 0, 0]}>
                      <group name="Mesh16" position={[0, 0, 0]} />
                    </group>
                    <group name="Group19" position={[0, 0, 0]}>
                      <group name="Mesh17" position={[0, 0, 0]} />
                    </group>
                    <group name="Group20" position={[0, 0, 0]}>
                      <group name="Mesh18" position={[0, 0, 0]} />
                    </group>
                    <group name="Group21" position={[0, 0, 0]}>
                      <group name="Mesh19" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh19_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh19_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                    <group name="Group5" position={[0, 0, 0]}>
                      <group name="Mesh3" position={[0, 0, 0]} />
                    </group>
                    <group name="Group6" position={[0, 0, 0]}>
                      <group name="Mesh4" position={[0, 0, 0]} />
                    </group>
                    <group name="Group7" position={[0, 0, 0]}>
                      <group name="Mesh5" position={[0, 0, 0]} />
                    </group>
                    <group name="Group8" position={[0, 0, 0]}>
                      <group name="Mesh6" position={[0, 0, 0]} />
                    </group>
                    <group name="Group9" position={[0, 0, 0]}>
                      <group name="Mesh7" position={[0, 0, 0]} />
                    </group>
                  </group>
                </group>
                <group name="Group40" position={[0, 0, 0]}>
                  <group name="__________________10" position={[0, 0, 0]}>
                    <group name="Group59" position={[0, 0, 0]}>
                      <group name="Mesh55" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh55_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh55_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                    <group name="Group60" position={[0, 0, 0]}>
                      <group name="Mesh56" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh56_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh56_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________11" position={[0, 0, 0]}>
                    <group name="Group61" position={[0, 0, 0]}>
                      <group name="Mesh57" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh57_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh57_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                    <group name="Group62" position={[0, 0, 0]}>
                      <group name="Mesh58" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh58_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh58_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________12" position={[0, 0, 0]}>
                    <group name="Group63" position={[0, 0, 0]}>
                      <group name="Mesh59" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh59_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh59_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                    <group name="Group64" position={[0, 0, 0]}>
                      <group name="Mesh60" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh60_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh60_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________13" position={[0, 0, 0]}>
                    <group name="Group65" position={[0, 0, 0]}>
                      <group name="Mesh61" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh61_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh61_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                    <group name="Group66" position={[0, 0, 0]}>
                      <group name="Mesh62" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh62_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh62_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________14" position={[0, 0, 0]}>
                    <group name="Group67" position={[0, 0, 0]}>
                      <group name="Mesh63" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh63_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh63_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                    <group name="Group68" position={[0, 0, 0]}>
                      <group name="Mesh64" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh64_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh64_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________15" position={[0, 0, 0]}>
                    <group name="Group69" position={[0, 0, 0]}>
                      <group name="Mesh65" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh65_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh65_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                    <group name="Group70" position={[0, 0, 0]}>
                      <group name="Mesh66" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh66_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh66_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________16" position={[0, 0, 0]}>
                    <group name="Group71" position={[0, 0, 0]}>
                      <group name="Mesh67" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh67_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh67_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                    <group name="Group72" position={[0, 0, 0]}>
                      <group name="Mesh68" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh68_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh68_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________17" position={[0, 0, 0]}>
                    <group name="Group73" position={[0, 0, 0]}>
                      <group name="Mesh69" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh69_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh69_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                    <group name="Group74" position={[0, 0, 0]}>
                      <group name="Mesh70" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh70_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh70_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="__________________18" position={[0, 0, 0]}>
                    <group name="Group75" position={[0, 0, 0]}>
                      <group name="Mesh71" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh71_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh71_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                    <group name="Group76" position={[0, 0, 0]}>
                      <group name="Mesh72" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh72_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh72_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="Group41" position={[0, 0, 0]}>
                    <group name="Group42" position={[0, 0, 0]}>
                      <group name="Mesh38" position={[0, 0, 0]} />
                    </group>
                    <group name="Group43" position={[0, 0, 0]}>
                      <group name="Mesh39" position={[0, 0, 0]} />
                    </group>
                    <group name="Group44" position={[0, 0, 0]}>
                      <group name="Mesh40" position={[0, 0, 0]} />
                    </group>
                    <group name="Group45" position={[0, 0, 0]}>
                      <group name="Mesh41" position={[0, 0, 0]} />
                    </group>
                    <group name="Group46" position={[0, 0, 0]}>
                      <group name="Mesh42" position={[0, 0, 0]} />
                    </group>
                    <group name="Group47" position={[0, 0, 0]}>
                      <group name="Mesh43" position={[0, 0, 0]} />
                    </group>
                    <group name="Group48" position={[0, 0, 0]}>
                      <group name="Mesh44" position={[0, 0, 0]} />
                    </group>
                    <group name="Group49" position={[0, 0, 0]}>
                      <group name="Mesh45" position={[0, 0, 0]} />
                    </group>
                    <group name="Group50" position={[0, 0, 0]}>
                      <group name="Mesh46" position={[0, 0, 0]} />
                    </group>
                    <group name="Group51" position={[0, 0, 0]}>
                      <group name="Mesh47" position={[0, 0, 0]} />
                    </group>
                    <group name="Group52" position={[0, 0, 0]}>
                      <group name="Mesh48" position={[0, 0, 0]} />
                    </group>
                    <group name="Group53" position={[0, 0, 0]}>
                      <group name="Mesh49" position={[0, 0, 0]} />
                    </group>
                    <group name="Group54" position={[0, 0, 0]}>
                      <group name="Mesh50" position={[0, 0, 0]} />
                    </group>
                    <group name="Group55" position={[0, 0, 0]}>
                      <group name="Mesh51" position={[0, 0, 0]} />
                    </group>
                    <group name="Group56" position={[0, 0, 0]}>
                      <group name="Mesh52" position={[0, 0, 0]} />
                    </group>
                    <group name="Group57" position={[0, 0, 0]}>
                      <group name="Mesh53" position={[0, 0, 0]} />
                    </group>
                    <group name="Group58" position={[0, 0, 0]}>
                      <group name="Mesh54" position={[0, 0, 0]}>
                        <mesh
                          name="Mesh54_FrontColor_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh54_FrontColor_0.geometry}
                          material={materials['FrontColor.001']}
                          position={[0, 0, 0]}
                        />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Group77" position={[0, 0, 0]}>
                  <group name="WoodBar1_1" position={[0, 0, 0]}>
                    <group name="Mesh73" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh73_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh73_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_10" position={[0, 0, 0]}>
                    <group name="Mesh82" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh82_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh82_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_11" position={[0, 0, 0]}>
                    <group name="Mesh83" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh83_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh83_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_12" position={[0, 0, 0]}>
                    <group name="Mesh84001" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh84_FrontColor_0001"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh84_FrontColor_0001.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_13" position={[0, 0, 0]}>
                    <group name="Mesh85" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh85_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh85_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_14" position={[0, 0, 0]}>
                    <group name="Mesh86" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh86_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh86_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_15" position={[0, 0, 0]}>
                    <group name="Mesh87" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh87_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh87_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_16" position={[0, 0, 0]}>
                    <group name="Mesh88" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh88_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh88_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_17" position={[0, 0, 0]}>
                    <group name="Mesh89" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh89_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh89_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_18" position={[0, 0, 0]}>
                    <group name="Mesh90" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh90_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh90_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_19" position={[0, 0, 0]}>
                    <group name="Mesh91" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh91_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh91_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_2" position={[0, 0, 0]}>
                    <group name="Mesh74" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh74_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh74_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_20" position={[0, 0, 0]}>
                    <group name="Mesh92" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh92_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh92_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_21" position={[0, 0, 0]}>
                    <group name="Mesh93" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh93_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh93_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_3" position={[0, 0, 0]}>
                    <group name="Mesh75" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh75_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh75_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_4" position={[0, 0, 0]}>
                    <group name="Mesh76" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh76_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh76_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_5" position={[0, 0, 0]}>
                    <group name="Mesh77" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh77_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh77_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_6" position={[0, 0, 0]}>
                    <group name="Mesh78" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh78_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh78_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_7" position={[0, 0, 0]}>
                    <group name="Mesh79" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh79_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh79_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_8" position={[0, 0, 0]}>
                    <group name="Mesh80" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh80_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh80_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                  <group name="WoodBar1_9" position={[0, 0, 0]}>
                    <group name="Mesh81" position={[0, 0, 0]}>
                      <mesh
                        name="Mesh81_FrontColor_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh81_FrontColor_0.geometry}
                        material={materials['FrontColor.001']}
                        position={[0, 0, 0]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="mesafuera"
          position={[-16.583, -1.285, -2.383]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.171}>
          <group
            name="d42622b1b79f4125a2f8d32e86ccc560fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="RootNode003">
              <group
                name="Chair1"
                position={[717.132, 167.077, -232.951]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={120}>
                <mesh
                  name="Chair1_Metal028_2K_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair1_Metal028_2K_0.geometry}
                  material={materials.Metal028_2K}
                />
                <mesh
                  name="Chair1_Wood049_2K_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair1_Wood049_2K_0.geometry}
                  material={materials.Wood049_2K}
                />
              </group>
              <group
                name="Chair2"
                position={[598.735, 167.077, -232.951]}
                rotation={[-Math.PI / 2, 0, -3.016]}
                scale={120}>
                <mesh
                  name="Chair2_Metal028_2K_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair2_Metal028_2K_0.geometry}
                  material={materials.Metal028_2K}
                />
                <mesh
                  name="Chair2_Wood049_2K_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair2_Wood049_2K_0.geometry}
                  material={materials.Wood049_2K}
                />
              </group>
              <group
                name="Chair3"
                position={[717.132, 167.077, -303.102]}
                rotation={[-Math.PI / 2, 0, 0.238]}
                scale={120}>
                <mesh
                  name="Chair3_Metal028_2K_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair3_Metal028_2K_0.geometry}
                  material={materials.Metal028_2K}
                />
                <mesh
                  name="Chair3_Wood049_2K_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair3_Wood049_2K_0.geometry}
                  material={materials.Wood049_2K}
                />
              </group>
              <group
                name="Chair4"
                position={[598.735, 167.077, -313.251]}
                rotation={[-Math.PI / 2, 0, 2.737]}
                scale={120}>
                <mesh
                  name="Chair4_Metal028_2K_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair4_Metal028_2K_0.geometry}
                  material={materials.Metal028_2K}
                />
                <mesh
                  name="Chair4_Wood049_2K_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chair4_Wood049_2K_0.geometry}
                  material={materials.Wood049_2K}
                />
              </group>
              <group
                name="Table002"
                position={[627.147, 203.377, -224.788]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={120}>
                <mesh
                  name="Table_Metal028_2K_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Table_Metal028_2K_0.geometry}
                  material={materials.Metal028_2K}
                />
                <mesh
                  name="Table_Wood049_2K_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Table_Wood049_2K_0.geometry}
                  material={materials.Wood049_2K}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="bbq"
          position={[-8.904, 0, -8.201]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.011, 0.01, 0.01]}>
          <group name="00e7dcf0853a4a1993b6cc7bb2130e7efbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2002">
              <group name="RootNode004">
                <group
                  name="Dummy001"
                  position={[0.732, 63.293, 4.148]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={2.54}>
                  <group
                    name="Cylinder001"
                    position={[-23.708, 1.294, 13.63]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={[1, 1.104, 1]}>
                    <mesh
                      name="Cylinder001_07_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Cylinder001_07_-_Default_0'].geometry}
                      material={materials['07_-_Default']}
                    />
                    <mesh
                      name="Cylinder001_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Cylinder001_08_-_Default_0'].geometry}
                      material={materials['08_-_Default']}
                    />
                    <mesh
                      name="Cylinder001_10_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Cylinder001_10_-_Default_0'].geometry}
                      material={materials['10_-_Default']}
                    />
                    <mesh
                      name="Cylinder001_13_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Cylinder001_13_-_Default_0'].geometry}
                      material={materials['13_-_Default']}
                    />
                    <mesh
                      name="Cylinder001_14_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Cylinder001_14_-_Default_0'].geometry}
                      material={materials['14_-_Default']}
                    />
                    <mesh
                      name="Cylinder001_15_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Cylinder001_15_-_Default_0'].geometry}
                      material={materials['15_-_Default']}
                    />
                    <mesh
                      name="Cylinder001_19_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Cylinder001_19_-_Default_0'].geometry}
                      material={materials['19_-_Default']}
                    />
                    <mesh
                      name="Cylinder001_21_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Cylinder001_21_-_Default_0'].geometry}
                      material={materials['21_-_Default.001']}
                    />
                    <mesh
                      name="Cylinder001_22_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Cylinder001_22_-_Default_0'].geometry}
                      material={materials['22_-_Default']}
                    />
                  </group>
                  <group
                    name="Object001"
                    position={[0.789, 18.571, 13.63]}
                    rotation={[-2.004, Math.PI / 2, 0]}
                    scale={[1, 1.104, 1]}>
                    <group name="Object_16" position={[0, -15.652, -24.497]}>
                      <mesh
                        name="Object001_07_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object001_07_-_Default_0'].geometry}
                        material={materials['07_-_Default']}
                      />
                      <mesh
                        name="Object001_08_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object001_08_-_Default_0'].geometry}
                        material={materials['08_-_Default']}
                      />
                      <mesh
                        name="Object001_09_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object001_09_-_Default_0'].geometry}
                        material={materials['09_-_Default']}
                      />
                      <mesh
                        name="Object001_20_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object001_20_-_Default_0'].geometry}
                        material={materials['20_-_Default']}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="Pergola001"
          position={[-14.777, 0.108, -9.579]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.001}>
          <group
            name="3ce74f31fd3a42bea547c4fe34622b52fbx001"
            position={[0, -0.001, 0]}
            rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode002" position={[0, 0, 0]}>
              <group name="Model001" position={[0, 0, 0]}>
                <group name="Group3001" position={[0, 0, 0]}>
                  <group name="__________________1001" position={[0, 0, 0]}>
                    <group name="Group22001" position={[0, 0, 0]}>
                      <group name="Mesh20001" position={[0, 0, 0]} />
                    </group>
                  </group>
                  <group name="__________________2001" position={[0, 0, 0]}>
                    <group name="Group24001" position={[0, 0, 0]}>
                      <group name="Mesh22001" position={[0, 0, 0]} />
                    </group>
                  </group>
                  <group name="__________________3001" position={[0, 0, 0]}>
                    <group name="Group26001" position={[0, 0, 0]}>
                      <group name="Mesh24001" position={[0, 0, 0]} />
                    </group>
                  </group>
                  <group name="__________________4001" position={[0, 0, 0]}>
                    <group name="Group28001" position={[0, 0, 0]}>
                      <group name="Mesh26001" position={[0, 0, 0]} />
                    </group>
                  </group>
                  <group name="__________________5001" position={[0, 0, 0]}>
                    <group name="Group30001" position={[0, 0, 0]}>
                      <group name="Mesh28001" position={[0, 0, 0]} />
                    </group>
                  </group>
                  <group name="__________________6001" position={[0, 0, 0]}>
                    <group name="Group32001" position={[0, 0, 0]}>
                      <group name="Mesh30001" position={[0, 0, 0]} />
                    </group>
                  </group>
                  <group name="__________________7001" position={[0, 0, 0]}>
                    <group name="Group34001" position={[0, 0, 0]}>
                      <group name="Mesh32001" position={[0, 0, 0]} />
                    </group>
                  </group>
                  <group name="__________________8001" position={[0, 0, 0]}>
                    <group name="Group36001" position={[0, 0, 0]}>
                      <group name="Mesh34001" position={[0, 0, 0]} />
                    </group>
                  </group>
                  <group name="__________________9001" position={[0, 0, 0]}>
                    <group name="Group38001" position={[0, 0, 0]}>
                      <group name="Mesh36001" position={[0, 0, 0]} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/modelHome.glb')
export default ModelHome
