export const infoContacto = {
  es: {
    titulo: "Contáctanos",
    tituloForm: "Formulario de Contacto",
    placeholderUsuario: "Escribe tu nombre",
    placeholderEmail: "Escribe tu email",
    placeholderMensaje: "Escribe aquí tu mensaje",
    direccion: "Dirección",
    contacto: "Contacto",
    boton: "Enviar",
    enviado: "Enviando...",
    exito: "¡Mensaje enviado con éxito!",
    contactarFuturo: "Nos pondremos en contacto lo antes posible.",
  },
  en: {
    titulo: "Contact Us",
    tituloForm: "Contact Form",
    placeholderUsuario: "Write your name",
    placeholderEmail: "Write your email",
    placeholderMensaje: "Write your message here",
    direccion: "Address",
    contacto: "Contact",
    boton: "Send",
    enviado: "Sending...",
    exito: "Form Submitted Successfully!",
    contactarFuturo: "We will get in touch as soon as possible"
  },
  fr: {
    titulo: "Contactez-nous",
    tituloForm: "Formulaire de Contact",
    placeholderUsuario: "Écrivez votre nom",
    placeholderEmail: "Écrivez votre email",
    placeholderMensaje: "Écrivez votre message ici",
    direccion: "Adresse",
    contacto: "Contact",
    boton: "Envoyer",
    enviado: "Envoi en cours...",
    exito: "Formulaire soumis avec succès !",
    contactarFuturo: "Nous vous contacterons dès que possible."
  },
  de: {
    titulo: "Kontaktieren Sie uns",
    tituloForm: "Kontaktformular",
    placeholderUsuario: "Schreiben Sie Ihren Namen",
    placeholderEmail: "Schreiben Sie Ihre E-Mail",
    placeholderMensaje: "Schreiben Sie hier Ihre Nachricht",
    direccion: "Adresse",
    contacto: "Kontakt",
    boton: "Senden",
    enviado: "Senden...",
    exito: "Formular erfolgreich eingereicht!",
    contactarFuturo: "Wir werden uns so schnell wie möglich bei Ihnen melden."
  },
  ru: {
    titulo: "Свяжитесь с нами",
    tituloForm: "Форма обратной связи",
    placeholderUsuario: "Введите ваше имя",
    placeholderEmail: "Введите ваш email",
    placeholderMensaje: "Введите ваше сообщение здесь",
    direccion: "Адрес",
    contacto: "Контакт",
    boton: "Отправить",
    enviado: "Отправка...",
    exito: "Сообщение успешно отправлено!",
    contactarFuturo: "Мы свяжемся с вами как можно скорее."
  },
  da: {
    titulo: "Kontakt os",
    tituloForm: "Kontaktformular",
    placeholderUsuario: "Skriv dit navn",
    placeholderEmail: "Skriv din e-mail",
    placeholderMensaje: "Skriv din besked her",
    direccion: "Adresse",
    contacto: "Kontakt",
    boton: "Send",
    enviado: "Sender...",
    exito: "Besked sendt succesfuldt!",
    contactarFuturo: "Vi kontakter dig så hurtigt som muligt."
  }
};
