export const infoNuestrosTrabajos = {
  es: { titulo: "Nuestros trabajos" },
  en: { titulo: "Our works" },
  fr: { titulo: "Nos réalisations" },
  de: { titulo: "Unsere Arbeiten" },
  da: { titulo: "Vores arbejde" },
  ru: { titulo: "Наши работы" },
};

export const imagesNuestrosTrabajos = [
  {
    imagen: "/assets/SliderTrabajos/Articulados/Articulado-1.webp",
    titulo: {
      es: "Toldo Articulado",
      en: "Articulated Awning",
      fr: "Store articulé",
      de: "Gelenkarmmarkise",
      da: "Ledarm-markise",
      ru: "Выдвижной навес",
    },
    descripcion: {
      es: "Articulado Extremo",
      en: "EXTREME",
      fr: "EXTREME",
      de: "EXTREME",
      da: "EXTREME",
      ru: "EXTREME",
    },
  },
  {
    imagen: "/assets/SliderTrabajos/Capotas/Capotas-1.webp",
    titulo: {
      es: "Capota",
      en: "Hoods",
      fr: "Capotes",
      de: "Hauben",
      da: "Hætter",
      ru: "Капюшоны",
    },
    descripcion: {
      es: "Articulado Extremo",
      en: "EXTREME",
      fr: "EXTREME",
      de: "EXTREME",
      da: "EXTREME",
      ru: "EXTREME",
    },
  },
  {
    imagen: "/assets/SliderTrabajos/Pergolas/Pergola-1.webp",
    titulo: {
      es: "Pérgola",
      en: "Pergola",
      fr: "Pergola",
      de: "Pergola",
      da: "Pergolaer",
      ru: "Пергола",
    },
    descripcion: {
      es: "Articulado Extremo",
      en: "EXTREME",
      fr: "EXTREME",
      de: "EXTREME",
      da: "EXTREME",
      ru: "EXTREME",
    },
  },
  {
    imagen: "/assets/SliderTrabajos/Cofres/Cofre-1.webp",
    titulo: {
      es: "Toldo Cofre",
      en: "Chest Awning",
      fr: "Store coffre",
      de: "Kassettenmarkise",
      da: "Kassette-markise",
      ru: "Кассетный навес",
    },
    descripcion: {
      es: "Articulado Extremo",
      en: "EXTREME",
      fr: "EXTREME",
      de: "EXTREME",
      da: "EXTREME",
      ru: "EXTREME",
    },
  },
  {
    imagen: "/assets/SliderTrabajos/Terrazas/Terraza-1.webp",
    titulo: {
      es: "Terraza",
      en: "Terrace",
      fr: "Terrasse",
      de: "Terrasse",
      da: "Terrasse",
      ru: "Терраса",
    },
    descripcion: {
      es: "Articulado Extremo",
      en: "EXTREME",
      fr: "EXTREME",
      de: "EXTREME",
      da: "EXTREME",
      ru: "EXTREME",
    },
  },
  {
    imagen: "/assets/SliderTrabajos/Verandas/Veranda-1.webp",
    titulo: {
      es: "Toldo Veranda",
      en: "Veranda Awning",
      fr: "Store véranda",
      de: "Veranda-Markise",
      da: "Veranda-markise",
      ru: "Навес для веранды",
    },
    descripcion: {
      es: "Articulado Extremo",
      en: "EXTREME",
      fr: "EXTREME",
      de: "EXTREME",
      da: "EXTREME",
      ru: "EXTREME",
    },
  },
  {
    imagen: "/assets/SliderTrabajos/Stores/Store-1.webp",
    titulo: {
      es: "Stores",
      en: "Stores",
      fr: "Stores",
      de: "Stores",
      da: "Stores",
      ru: "Шторы",
    },
    descripcion: {
      es: "Articulado Extremo",
      en: "EXTREME",
      fr: "EXTREME",
      de: "EXTREME",
      da: "EXTREME",
      ru: "EXTREME",
    },
  },
  {
    imagen: "/assets/SliderTrabajos/Velas/Vela-1.webp",
    titulo: {
      es: "Vela",
      en: "Sail",
      fr: "Voile d'ombrage",
      de: "Segelmarkise",
      da: "Sejlmarkise",
      ru: "Парусный тент",
    },
    descripcion: {
      es: "Articulado Extremo",
      en: "EXTREME",
      fr: "EXTREME",
      de: "EXTREME",
      da: "EXTREME",
      ru: "EXTREME",
    },
  },
];
