/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: fernandogilmiranda (https://sketchfab.com/fernandogilmiranda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/awning-a3cd8618bb91405fb8e475689690f537
Title: Awning
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Capota = (props) => {
  const { nodes, materials } = useGLTF('/models/tcapota.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={5.32}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Group_001_1_Mat_0.geometry}
            material={materials.material}
            position={[0, 322.796, 0]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/tcapota.glb')

export default Capota