/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 1-3D.com (https://sketchfab.com/1-3D.com)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/awning-312d002180124952b526b5396541b593
Title: Awning
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Cofre = (props) => {
  const { nodes, materials } = useGLTF('/models/tcofre.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Waterboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Canvas}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Hinges}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Metal}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/tcofre.glb')
export default Cofre
