/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ko_renders (https://sketchfab.com/ko_renders)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skyshadestm-sky-x-night-view-9bd4dc4b99e0452eb2c5285fa87e3e50
Title: SKYSHADES™ - Sky X - Night view
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Pergola = (props) => {
  const { nodes, materials } = useGLTF('/models/pergola.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2.geometry}
          material={materials['0056_Yellow']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_1.geometry}
          material={materials.Color_M03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3.geometry}
          material={materials.GDLM2_5011_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_1.geometry}
          material={materials.GDLM1___________1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_2.geometry}
          material={materials.auto_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_3.geometry}
          material={materials.auto_4}
        />
      </group>
    </group>
  )
}
export default Pergola
useGLTF.preload('/models/pergola.glb')
