//ELIGE COMODIDAD, ELIGE CALIDAD? HAY QUE REEMPLAZAR EL HOME PARA MOVIL, ES DEMASIADO TEXTO Y POCO ELEGANTE PARA LO QUE ES EL RESTO DE LA PAGINA
//COLOR DE SELECTS EN APPLE
//Cambiar saltos de lineas en infoBeneficios